### ISSUE TITLE
Missing MS Edge features

### ISSUE THREAD

**Issue by dstorey** [kpdecker/six-speed#10]
A few of the ES6 features left blank in Edge are supported behind a flag. Would be nice to enable via about:flags and include them. E.g. Classes, defaults, generators.

**Comment by jdalton** [comment]
\cc @bterlson @kangax

**Comment by kpdecker** [comment]
Flag in question:

> [3] Flagged features have to be enabled via "Enable experimental Javascript features" setting under about:flags

Right now this will need to be done manually (as the testing for Edge isn't automated due to lack of support from any of the cloud vendors). Any way we can automate the flag setting and/or the test execution?

**Comment by kpdecker** [comment]
Switched to using a local VM that has this flag always set. Data set updated.
