### ISSUE TITLE
Test babel in runtime and non-runtime mode

### ISSUE THREAD

**Issue by zloirock** [kpdecker/six-speed#12]
Polyfills tests for `babel` are not correct. Try it w/o `runtime` transformer, with `babel/polyfill`. `library` version `core-js` returns wrapped native collection instances for prevent pollution in native prototypes.

**Comment by zloirock** [comment]
For some tests more corect add different lines for `babel` and `babel` with `runtime` transformer.

**Comment by kpdecker** [comment]
I'm sorry I don't understand what you are trying to say. Can you please explain how these are incorrect?

**Comment by zloirock** [comment]
You testing `babel` with optional `runtime` transformer. This transformer designed for distributed modules - prevented global namespace pollution, and uses `library` version `core-js`. It's seriously differs from the standard version, including performance. For example, in `map-set` test result should be equal native `Map` / `Set`.

**Comment by kpdecker** [comment]
Unfortunately this is the only way to have any level of isolation from the Traceur implementation. Any thoughts on how these could be tested in isolation? If we can get that then I'm glad to have {Babel, Babel-Runtime, Babel-Loose} test cases, but until then we need to use the runtime version.

**Comment by zloirock** [comment]
Isolated context - for example, iframe, workers, vm?

**Comment by kpdecker** [comment]
As long as they are run in the same process as the other tests those should all work. Going to need a fair amount of investment in the test infrastructure to make that work but I don't THINK it will invalidate the test results any.

**Comment by zloirock** [comment]
:thumbsup:
