### ISSUE TITLE
Engines can look good by having slow ES5 implementations

### ISSUE THREAD

**Issue by domenic** [kpdecker/six-speed#15]
It might be better to compare to the fastest ES5 implementation, instead of the one from the corresponding engine.

**Comment by kpdecker** [comment]
While I'd love to have this, I worry about the feasibility. Running these tests in the cloud I don't have that much control over what is going on and any number of external factors could skew the data. With the internal comparisons that are done right now that's still somewhat an issue but at least the data concerns are isolated to one execution and the comparison is at least known to be within the same machine and process.

If there were resources that could let us run within a more stable environment, then this would be more feasible, of course.

**Comment by realityking** [comment]
At least for me this would be more about not downgrading performance when adopting ES6, so the current comparison is perfectly fine.

**Comment by kpdecker** [comment]
Closing this as the goal here isn't cross browser comparison. Leaving those performance comparisons to full browser benchmarks.
