### ISSUE TITLE
Ideas for making the table more readable

### ISSUE THREAD

**Issue by simevidas** [kpdecker/six-speed#16]
1. Could you add table borders? As of right now, it is not very clear which rows belong to which feature.
   ![clear](https://cloud.githubusercontent.com/assets/716405/8399409/210512c8-1e0e-11e5-94da-3135a939117b.png)
2. An interesting enhancement would be to dynamically (with JavaScript) add background colors to the cells based on their content, e.g. “10x slower” would get a light red background, “100x slower” would get a darker red background, the “faster” cells would get shades of green. The exact color value would be computed from the multiplier integer.

It would be a simple script, and you could add a “Colorize” button to run it on the page.

**Comment by kpdecker** [comment]
1. This is probably the same issue as #14. Please take a look now.
2. Could do that, any thoughts on the exact colors used?

**Comment by simevidas** [comment]
Cool, I see the styles now in Firefox.

As for the colors, I find that [Wikipedia’s selection](https://en.wikipedia.org/wiki/Comparison_of_layout_engines_%28Cascading_Style_Sheets%29#Values) is a good choice (e.g. #9F9 for green, #F99 for red, could be the max background for the highest multipliers 1000x and up).
