### ISSUE TITLE
Automate edge testing

### ISSUE THREAD

**Issue by kpdecker** [kpdecker/six-speed#25]
Edge is the last browser preventing this from being completely croned.

Sauce has added support but the experimental JS flag is not enabled by default. 

Either need to look at using Selenium to push this config flag or automating the VM environment setup on the automation machine.

@dstorey @jdalton @bterlson @kangax et al: Any input on following?
1. If set does the experimental flag go into effect on the next page load or is there any sort of browser restart required?
2. Is there any autoupdate options that are available for the modern.ie VMs that can be used vs. pulling whole VM each time if I go the route of hosting own VM (which I'd prefer to avoid lag in potential Sauce rollouts)

**Comment by dstorey** [comment]
@molant for the VMs

**Comment by molant** [comment]
1. You need to restart the browser to activate the features.
2. For 2 you will need to be part of the insiders to get the updates. You will have to get the whole update for the OS, cant get inky Edge. We can look into having the consumer VMS and the insider flights in modern.ie but not sure that will help you a lot (still need to download a whole vm).

Hope this answers your questions.

**Comment by kpdecker** [comment]
Thanks!
1. Is there any way that I can enable the flag from the command line prior to launching the browser for the first time? Registry setting or similar?
2. I'll likely try to cron the download too (the whole suite takes 90min plus so whats another large download :) ). Is there a public service that generates the `edgePortal.vms` object or will I have to scrape?

**Comment by molant** [comment]
1. There is probably one. Maybe @bterlson knows more? You can try saving your user config hive before and after doing the change via about:flags and do a diff see if something appears.
2. https://dev.modern.ie/api/tools/vms/ is probably the link you want :)

**Comment by kpdecker** [comment]
1. `HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.microsoftedge_8wekyb3d8bbwe\MicrosoftEdge\ExperimentalFeatures\ExperimentalJS` being set to DWORD:1 is what happens when setting the value through the config UI. My windows hacking days stopped circa XP so I'm really not sure how app containers work or if that 8w... value is a uniquifier that is going to make scripting difficult.
2. Thanks, works like a charm.

**Comment by molant** [comment]
Don't think that key is going to change. The app is stored in `C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe` :)

**Comment by kpdecker** [comment]
Slowly making progress on this, but it feels like there is some flakiness with either the VM or the VM Tools. For some unknown reason it seems to hang, sometimes at the boot screen (Windows icon, spinning loading indicator that eventually freezes) sometimes afterwards on a black screen. In both circumstances the CPU pegs at 100% and the vmrun commands generally hang. This doesn't necessarily seem to be tied to the first boot or not, any clean shutdown and startup may see it. Not sure if anyone has experienced with such things or knows of causes/work arounds.

**Comment by molant** [comment]
I think you are the first one I see with this issue. 
What VM are you using?
Did it happened the first time you booted the machine? Maybe you can download the VM again, take a snapshot before starting it and then reapply the saved state before each run?

**Comment by kpdecker** [comment]
VMWare Fusion 8.0.1

Actually seems to occur more on first boot than not. A force restart after either of these cases seems to fix, usually. Unfortunately this is really hard to automate as I can't seem to find any probes via `vmrun` that let me detect.

Install is scripted via [this](https://github.com/kpdecker/browser-downloader/blob/master/src/vm.js). Perhaps could be related to the issues.

**Comment by kpdecker** [comment]
There also were some windows update process that seem to pop up from time to time which throws a wrench in the works. Starting to think that it might be better to manually manage the VMs and get a known good snapshot for each version rather than trying to automate the init process completely.

**Comment by kpdecker** [comment]
Got something that seems fairly stable now with a snapshot after all init processes have been done in the VM as well as sanity in the automated portions to verify that this is in the correct state. Thanks for all of the help (Updated numbers pushed for those that are curious)
