### ISSUE TITLE
I can't run the test

### ISSUE THREAD

**Issue by netheril96** [kpdecker/six-speed#30]
I am a newbie to the JS world, and I would like to benchmark some ES6 features myself. I cloned this repository, run `npm install` to install all dependencies, then `npm start` to start the server to manually test in browser. But when I open `http://localhost:9999` in my browser, I get `403 Forbidden` response. What is wrong?

**Comment by kpdecker** [comment]
I don't know how valuable this is as a learning tool, the execution it targeted primarily at data collection. You might want to look at something like jsperf.com for something that is a bit more interactive.

That being said, are there any errors in the logs when running the npm commands?
