### ISSUE TITLE
Test Closure Compiler

### ISSUE THREAD

**Issue by caridy** [kpdecker/six-speed#33]
Google Closure Compiler support 99% of the ES6 grammar, will be great to compare the results against the other transpilers.

**Comment by zloirock** [comment]
> Google Closure Compiler support 99% of the ES6

[`compat-table` does not agree with you ;)](http://kangax.github.io/compat-table/es6/#closure)

**Comment by caridy** [comment]
@zloirock interesting, cc'ing google folks.

Obviously the 35% score on compat-table is about ES6 features, not only about ES6 grammar, while six-speed is mostly about new grammar.

/cc @littledan, @dimvar

**Comment by kangax** [comment]
@caridy not sure what you mean by features vs. grammar but compat table includes syntax as well; unless we tested google closure incorrectly (not enabling new syntax or some such)

**Comment by caridy** [comment]
@kangax by default, closure compiler will transpiler all new grammar (syntax) down to ES3, you could tweak that to target ES5 instead for the case of six-speed and compat-table.

I suspect compat-table is testing closure compiler with the default options, without using [externs](https://github.com/google/closure-compiler/tree/master/externs), which are equivalent to babel-polyfill, that's why you see all the built-ins and built-ins extensions not supported.

I'm not a expert in closure compiler, I will let @dimvar and @littledan to chime in. I just want to make sure that we take closure compiler into consideration.

**Comment by zloirock** [comment]
Only ~35% of a `compat-table` ES6 result is built-ins result. [Anyway, `Closure` supports more ES6 features than `TypeScript` ;)](http://www.slideshare.net/teppeis/closure-compiler-updates-for-es6)

**Comment by dimvar** [comment]
Here is the doc about ES6 support in the compiler: https://github.com/google/closure-compiler/wiki/ECMAScript6

Did you have a question about whether some specific feature is supported?

**Comment by caridy** [comment]
@dimvar I think that documentation is incomplete, it only talks about grammar, but not all other features in ES6, let's say `WeakMap` or `Promise`, etc. Babel includes a section about the polyfill to support a full ES6 Environment (e.g.: https://babeljs.io/docs/usage/polyfill/), and even though closure compiler has a similar thing via `externs`, it is hard for people to make sense of it, that's probably why @kangax's compat-table didn't take that into consideration.

As for six-speed, it will be great is you guys can validate that closure can handle all the tests required to be added to the result table, that might help @kpdecker to add closure here, maybe a pull request?

**Comment by dimvar** [comment]
To rewrite the polyfills, you need to set this compiler option: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilerOptions.java#L792
I think there isn't a flag for it at the moment, but we'll turn it on by default soon, maybe in the next release? CC @shicks

**Comment by shicks** [comment]
I don't have concrete plans to turn it on by default externally. We can't do that unless we add a flag to turn it off, at any rate.

**Comment by caridy** [comment]
@zloirock @shicks whether that's turn on by default or not, it is debatable, babel doesn't do that automatically (IIRC), but having a very simple and intuitive way to do so is what really matters.

**Comment by zloirock** [comment]
@caridy most `babel` features just will not work without it. BTW https://github.com/kangax/compat-table/pull/741#issuecomment-179923364

**Comment by kpdecker** [comment]
Glad to include this in the tests as long as they are automated and can run under OSX. I don't have time to wire this up, but glad to pull in a PR and include in my weekly test exec. Might be as simple as adding another permutation [here](https://github.com/kpdecker/six-speed/blob/f0d7eb4c15dad7d2ede4076d6213249fcb40f737/tasks/build.js#L103), but this should be tested out.
