### ISSUE TITLE
What does "Identical" mean?

### ISSUE THREAD

**Issue by onlywei** [kpdecker/six-speed#35]
What is the performance "Identical" to?

**Comment by kpdecker** [comment]
The ES5 baseline tests for that engine version on that particular benchmark run. Ex. comparing 
https://github.com/kpdecker/six-speed/blob/master/tests/arrow-args/arrow-args.es5 to the various ES6 modes of this https://github.com/kpdecker/six-speed/blob/master/tests/arrow-args/arrow-args.es6
