### ISSUE TITLE
ES5 test on arrow function declaration is inaccurate

### ISSUE THREAD

**Issue by rmcvey** [kpdecker/six-speed#36]
[This](https://github.com/kpdecker/six-speed/blob/master/tests/arrow-declare/arrow-declare.es5) is not an apples-to-apples comparison as your closure does not inherit the parent scope like an arrow function does. This would be a more accurate test (which jsperf reported as being 89% slower than the current test):

```
var obj = {
  value: 42,
  fn: function() {
    return function() {
      return this.value;
    }.bind(this);
  }
};
```

**Comment by kpdecker** [comment]
This project was not intended to test known poor cases to provide benefit to one side or the other. It's intent was to show how reasonably optimized ES5 code, compares to the "naive" implementation of ES6 code, i.e. ignoring the performance blowing edge cases that most people won't take into account when rolling their own ES5 code.

WRT bind itself, as you note it is horribly unoptimized and I personally avoided it like the plague prior to transitioning to ES6 code. The transpilers do as well, opting for the closure version whenever possible to avoid unnecessary performance overhead. 

```
var obj = {
  value: 42,
  fn: function fn() {
    var _this = this;

    return function () {
      return _this.value;
    };
  }
};
```

Example [here](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%0Avar%20obj%20%3D%20%7B%0A%20%20value%3A%2042%2C%0A%20%20fn%3A%20function%28%29%20%7B%0A%20%20%20%20return%20%28%29%20%3D%3E%20this.value%3B%0A%20%20%7D%0A%7D%3B%0A%0Avar%20fn%20%3D%20obj.fn%28%29%3B%0AassertEqual%28fn%28%29%2C%2042%29%3B%0A%0Atest%28function%28%29%20%7B%0A%20%20fn%28%29%3B%0A%7D%29%3B%0A)

At one point I did have a bind test in addition to the closure, but it seemed of little value and when the tests ballooned to 2 hours of execution time, I dropped it as it felt like unnecessary overhead to demonstrate a performance issue in an ES5 feature.
