### ISSUE TITLE
Array destructuring into an function call is not represented

### ISSUE THREAD

**Issue by MMeent** [kpdecker/six-speed#37]
At the spread benchmarks, calling functions with spreaded arrays is not being benchmarked. I propose something like the following ES6 code to be benchmarked:

```
// ES6
function fn(a, b, c, d, e) {
  return c;
}

var list = [1, 2, 3]

//assertEqual(fn(), undefined);
//assertEqual(fn(...list), 3);
assertEqual(fn(3, 2, ...list), 1);
assertEqual(fn(0, ...list, 4), 2);

test(function() {
//fn();
//fn(...list); // equivalent to fn(0, 1, 2);
  fn(3, 2, ...list); // equivalent to fn(3, 2, 1, 2, 3);
  fn(0, ...list, 4); // equivalent to fn(0, 1, 2, 3, 4);
});
```

As far as I know this makes use of the most powerful features of ES6 spread in function calls, though I'm not yet sure if all these calls are nescessary, so I commented 2/4 out as these are trivial to implement in ES5. I'm also not quite sure how I would implement `fn(0, ...list, 4);` into ES5.

**Comment by kpdecker** [comment]
Glad to add to the test suite if you want to submit a PR (See https://github.com/kpdecker/six-speed/issues/38#issuecomment-191040923 regarding data.json)

**Comment by kpdecker** [comment]
Tracking under #40
