### ISSUE TITLE
Suggest separate const test and let test

### ISSUE THREAD

**Issue by hax** [kpdecker/six-speed#44]
See https://gist.github.com/hax/e70086e5749adbba352b21ec97db251a

It seems `const` has same performance as `var` in V8 (maybe a little faster in new versions), but `let` is far from optimized.  So I suggest separate `const` test and `let` test.

**Comment by kpdecker** [comment]
If you want to submit a PR, I'd be glad to talk about the changes. (One note, I'll run the tests again in my test environment so no need to include data.json changes with the output)

**Comment by hax** [comment]
I revisit the performance tests, and find that it's V8 special optimization which will utilize multi-core for loops in some cases, but `let` will forbidden such optimization. Consider the programmers could use Worker, and SIMD, Atomics to explicitly utilize multi-core, I guess we'd better drop such optimization. So I withdraw this issue.
