### ISSUE TITLE
Upgrade TypeScript?

### ISSUE THREAD

**Issue by styfle** [kpdecker/six-speed#48]
It looks like the version of TypeScript used is about a year old. The current version is 1.8.10 and I believe 2.0.0 should be out soon.

Additionally, `transpile()` should probably pass the `TypeScript.ScriptTarget.ES5` parameter.

**Comment by kpdecker** [comment]
```
    "typescript": "^1.5.3",
```

Includes 1.8.10 when the tests are run. It won't include 2.0 but once that's out, glad to accept a PR with whatever changes necessary.

If the typescript API is not being called correctly, glad to accept a PR with the necessary changes (Don't include data updates as I try to normalize those by running everything at the same time on the same machine)
