### ISSUE TITLE
ES6 tests run against polyfills

### ISSUE THREAD

**Issue by kpdecker** [kpdecker/six-speed#6]
Traceur polyfills the global space, allowing some tests that don't have syntax changes to run under ES6 mode when otherwise invalid.

Promises, Symbol, Set, Map all need to have some sort of check to invalidate the test if polyfilled.

**Comment by zloirock** [comment]
Polyfills tests for `babel` are not correct. Try it w/o `runtime` transformer.

**Comment by kpdecker** [comment]
Please elaborate under a new issue.

**Comment by zloirock** [comment]
Ok.
