### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by tedivm** [kpdecker/six-speed#60]
Can you update the website using the latest version of node? I'm curious how recent improvements have changed things.

**Comment by C-Lodder** [comment]
@tedivm Here are the latest tests I've performed incase you were interested

- **Node 10.13.0**
- **Chrome 70**
- **Firefox 63**
- **Edge 17**

![screenshot_2018-11-21 screenshot](https://user-images.githubusercontent.com/2019801/48854289-713ed800-eda9-11e8-8b22-b92efbabf88a.png)

**Comment by C-Lodder** [comment]
Tests have been updated: http://incaseofstairs.com/six-speed/
