### ISSUE TITLE
Add Node 8.3+ (v8 6.0) benchmarks

### ISSUE THREAD

**Issue by schmod** [kpdecker/six-speed#64]
Node 8 is now LTS, and uses an upgraded version of v8 that [substantially improves performance](https://github.com/davidmarkclements/v8-perf) in some areas.

Any way we can re-run the suite and publish the results for the current versions of Chrome and Node?

**Comment by bforbis** [comment]
How about node 10, which goes LTS in 2 weeks?

**Comment by kpdecker** [comment]
I don't have the time to continue to maintain this project. Glad to hand over the reigns if there is an interested party.

**Comment by C-Lodder** [comment]
@schmod @bforbis  see: https://github.com/kpdecker/six-speed/issues/60

**Comment by C-Lodder** [comment]
Added tests for Node 10.15.1 - http://incaseofstairs.com/six-speed/
