### ISSUE TITLE
Results over time

### ISSUE THREAD

**Issue by kane-mason** [kpdecker/six-speed#65]
We expect browser implementations of new feature sets over time to improve, is it possible to re-perform these tests every few months, or every year?

**Comment by C-Lodder** [comment]
Here are the latest tests I've performed:

- **Node 10.13.0**
- **Chrome 70**
- **Firefox 63**
- **Edge 17**

![screenshot_2018-11-21 screenshot](https://user-images.githubusercontent.com/2019801/48854244-51a7af80-eda9-11e8-83ad-70b18b5d2b58.png)

**Comment by sbmadhav** [comment]
@C-Lodder - can you please publish this to the website?

**Comment by C-Lodder** [comment]
@sbmadhav I've re-run the Node tests and pushed to the live site.

**Comment by sbmadhav** [comment]
Thanks!
