### ISSUE TITLE
No such thing as IE12

### ISSUE THREAD

**Issue by dstorey** [kpdecker/six-speed#9]
Would it be possible to change IE12 to Microsoft Edge? There isn’t an IE12.

**Comment by domenic** [comment]
Maybe just use the JS engine, so instead of "IE" it's "Chakra".

**Comment by jdalton** [comment]
I dig the engine names though that gets weird around Node/Chrome. Either way I've got a PR on my local with the MS Edge branding set. @kpdecker let me know and I can tweak it to Chakra or fire it off as is.

**Comment by kpdecker** [comment]
I think product name is better TBH as V8 could mean any number of things and features can be disabled via compiler flags, etc. (I'm assuming) That being said I am making one exception for tests coming from nightly builds as I only have the WebKit version number and no blessed next version name from the folks at Apple.

Re: PR, I have the same locally that also have the (to be tested) WebKit changes so I hope to have this done after I complete a run through of the test suite.
